version: '2'
services:
  cgtd:
    build: .
    links:
     - ipfs
    depends_on:
      - ipfs
    ports:
     - "5000:5000"
    volumes: 
      - .:/app
      - ./data:/data
    env_file:
      - ./env
  ipfs:
    image: ipfs/go-ipfs:release
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs
    ports:
      - "8080:8080"
      - "4001:4001"
      - "4002:4002/udp"
